### ISSUE TITLE
CR4.0 - Users need to re-enter book image

### ISSUE THREAD

**Issue by BaitiNoor** [BaitiNoor/Book-Store-SCM#5]
The book picture does not appear on edit page. To fix the bugs so that the photo of the book will appear on the edit page

**Comment by BaitiNoor** [comment]
Dear team, kindly update the progress of Change Request.

**Comment by hazirah996** [comment]
Dear Project Manager CR4.0 were still incomplete yet because of the issue on how the program is create before this and to fix this it may take an effect on other program.

**Comment by BaitiNoor** [comment]
CR is rejected due to error in source code

**Comment by BaitiNoor** [comment]
CR rejected due to error in source code
