### ISSUE TITLE
CR8.0 - Sort table in view book page in alphabetically

### ISSUE THREAD

**Issue by BaitiNoor** [BaitiNoor/Book-Store-SCM#9]
Arranging book data in order

**Comment by hazirah996** [comment]
Dear project manager through this  comment I have attached the result of implementation of CR8.0 that have been done.

Thank you!

[CR8 Implementation - HazirahBintiMohdFaizal(52213219131).docx](https://github.com/BaitiNoor/Book-Store-SCM/files/6254183/CR8.Implementation.-.HazirahBintiMohdFaizal.52213219131.docx)

**Comment by BaitiNoor** [comment]
CR 8.0 has been completed
